# Generated by Django 5.1.4 on 2024-12-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BatchJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        choices=[
                            ("sync_matches", "Synchroniser les matchs du jour"),
                            (
                                "sync_matches_from_date",
                                "Synchroniser les matchs depuis une date",
                            ),
                            ("sync_matches_active", "Synchroniser les matchs actifs"),
                            (
                                "sync_predictions_all",
                                "Synchroniser toutes les prédictions",
                            ),
                            (
                                "sync_predictions_upcoming",
                                "Synchroniser les prédictions à venir",
                            ),
                            ("sync_stats", "Synchroniser les stats"),
                            (
                                "sync_stats_live",
                                "Synchroniser les stats des matchs en cours",
                            ),
                            ("sync_stats_force", "Synchroniser stats matchs terminés"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "timing",
                    models.IntegerField(
                        blank=True, help_text="Intervalle en minutes", null=True
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("is_running", models.BooleanField(default=False)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
